server:
  port: 8001

spring:
  thymeleaf:
    cache: true
    
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      
#默认使用配置
  
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.0.14:3306/Xproject?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false

    username: admin
    password: slc961031
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.slc.XProject.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


