server:
  port: 8001
  #ssl:
  #  protocol: TLS
  #  key-store: classpath:keystore.p12
  #  key-store-password: 'slc961031!'
  #  keyStoreType: PKCS12
  #  keyAlias: tomcat
    
spring:
  thymeleaf:
    cache: true
   
 
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      
#默认使用配置
  
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/Xproject?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

    username: chiji
    password: '!QAZ2wsx'
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.slc.XProject.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


